
REM ANGIE
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Angie.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Angie.txt video_params\zParametersBundlingIndividualTimings.txt

REM COPYROOM200
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_CopyRoom200.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_CopyRoom200.txt video_params\zParametersBundlingIndividualTimings.txt

REM LIVE375
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Live375.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Live375.txt video_params\zParametersBundlingIndividualTimings.txt

REM OFFICE375
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Office375.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Office375.txt video_params\zParametersBundlingIndividualTimings.txt

REM MICHAEL
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Michael.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Michael.txt video_params\zParametersBundlingIndividualTimings.txt

REM GATES371
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Gates371.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Gates371.txt video_params\zParametersBundlingIndividualTimings.txt

REM GATES381
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Gates381.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Gates381.txt video_params\zParametersBundlingIndividualTimings.txt

REM STUDENT300
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Student300.txt video_params\zParametersBundlingFrameTimings.txt
x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Student300.txt video_params\zParametersBundlingIndividualTimings.txt

REM REM PANTRY200
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Pantry200.txt video_params\zParametersBundlingFrameTimings.txt
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Pantry200.txt video_params\zParametersBundlingIndividualTimings.txt
REM 
REM REM KITCHEN300
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Frame_Kitchen300.txt video_params\zParametersBundlingFrameTimings.txt
REM x64\Release\FriedLiver video_params\zParametersTimingLow_Individual_Kitchen300.txt video_params\zParametersBundlingIndividualTimings.txt