
x64\Release\FriedLiver video_params\zParametersVideo_Office375.txt zParametersBundlingDefault.txt
x64\Release\FriedLiver video_params\zParametersVideo_Student300.txt zParametersBundlingDefault.txt
x64\Release\FriedLiver video_params\zParametersVideo_Michael.txt zParametersBundlingDefault.txt

x64\Release\FriedLiver video_params\zParametersVideo_CopyRoom200.txt zParametersBundlingDefault.txt
x64\Release\FriedLiver video_params\zParametersVideo_Gates371.txt zParametersBundlingDefault.txt
x64\Release\FriedLiver video_params\zParametersVideo_Gates381.txt zParametersBundlingDefault.txt

x64\Release\FriedLiver video_params\zParametersVideo_Live375Low.txt zParametersBundlingDefault.txt
x64\Release\FriedLiver video_params\zParametersVideo_Angie.txt zParametersBundlingDefault.txt

REM x64\Release\FriedLiver video_params\zParametersVideo_Pantry200.txt zParametersBundlingDefault.txt
REM x64\Release\FriedLiver video_params\zParametersVideo_Kitchen300.txt zParametersBundlingDefault.txt
